export const cepages = [
  "Abouriou",
  "Aligoté",
  "Auxerrois",
  "Cabernet-Franc",
  "Cabernet-Sauvignon",
  "Carignan",
  "Chardonnay",
  "Chenin",
  "Cinsaut",
  "Clairette",
  "Colombard",
  "Fer Servadou",
  "Folle Blanche",
  "Gamay",
  "Gewurztraminer",
  "Grenache",
  "Grenache-blanc",
  "Grolleau",
  "Gros Manseng",
  "Jacquère",
  "Jurançon-noir",
  "Macabeu",
  "Malbec",
  "Marsanne",
  "Melon de Bourgogne",
  "Merlot",
  "Mondeuse",
  "Mourvèdre",
  "Muscadelle",
  "Muscat Petit Grain",
  "Muscat-blanc",
  "Nielluccio",
  "Petit Manseng",
  "Petit Verdot",
  "Picpoul",
  "Pinot-blanc",
  "Pinot-gris",
  "Pinot-meunier",
  "Pinot-noir",
  "Poulsard",
  "Riesling",
  "Roussanne",
  "Roussette",
  "Sauvignon",
  "Savagnin",
  "Sémilion",
  "Sylvaner",
  "Syrah",
  "Tannat",
  "Tibouren",
  "Trousseau",
  "Ugni-blanc",
  "Vermentino",
  "Viognier"
]