import { Data } from "@/utils/types"

export const data: Data[] = [
  {
    id: 1,
    date: new Date("2023-03-01"),
    bu: true,
    image: "",
    type: "vin rouge",
    domaine: "Domaine de la Cotelleraie",
    appelation: "Saint Nicolas de Bourgueil",
    terroir: "Chardonnay",
    region: "Pays de la Loire",
    annee: 2021,
    alcool: 13,
    cepage: {
      "Chardonnay": 70,
      "Pinot Noir": 30,
    },
    noteClem: 5,
    noteBen: 4,
    commentClem: "Bonne qualité de vin, goût bien frais, bonne éclaircie, très bonne bouteille, bonne goût, très bon goût",
    commentBen: "Bonne qualité de vin, bonne éclaircie, très bonne bouteille, bonne goût, très bon goût",
  },
  {
    id: 2,
    date: new Date("2022-09-11"),
    bu: true,
    image: "",
    type: "vin blanc",
    domaine: "Domaine Masson",
    appelation: "Apremont",
    terroir: "",
    region: "Savoie",
    annee: 2020,
    alcool: 13.5,
    cepage: {
      "Jacquère": 100,
    },
    noteClem: 5,
    noteBen: 4,
    commentClem: "Bonne qualité de vin, goût bien frais, bonne éclaircie, très bonne bouteille, bonne goût, très bon goût",
    commentBen: "Bonne qualité de vin, bonne éclaircie, très bonne bouteille, bonne goût, très bon goût",
  },
  {
    id: 3,
    date: new Date("2024-04-12"),
    bu: true,
    image: "",
    type: "vin rouge",
    domaine: "Domaine de Sigalière",
    appelation: "Pic Saint Loup",
    terroir: "",
    region: "Languedoc-Roussillon",
    annee: 2023,
    alcool: 14,
    cepage: {
      "Syrah": 60,
      "Grenache": 25,
      "Mourvèdre": 15,
    },
    noteClem: 5,
    noteBen: 4,
    commentClem: "Bonne qualité de vin, goût bien frais, bonne éclaircie, très bonne bouteille, bonne goût, très bon goût",
    commentBen: "Bonne qualité de vin, bonne éclaircie, très bonne bouteille, bonne goût, très bon goût",
  }
]