import { Data } from "@/utils/types"

export const data: Data[] = [
  {
    id: "saint_nicolas_de_bourgueil",
    date: new Date("2023-03-01"),
    bu: true,
    image: "",
    type: "vin rouge",
    domaine: "Domaine de la Cotelleraie",
    appelation: "Saint Nicolas de Bourgueil",
    region: "Pays de la Loire",
    annee: 2021,
    alcool: 13,
    cepages: [{ cepage: "Cabernet France", pourcentage: 90 }, { cepage: "Carbernet Sauvignon", pourcentage: 10 }],
    noteClem: 5,
    noteBen: 4,
    commentClem: "Bonne qualité de vin, goût bien frais, bonne éclaircie, très bonne bouteille, bonne goût, très bon goût",
    commentBen: "Bonne qualité de vin, bonne éclaircie, très bonne bouteille, bonne goût, très bon goût",
  },
  {
    id: "apremont",
    date: new Date("2022-09-11"),
    bu: true,
    image: "",
    type: "vin blanc",
    domaine: "Domaine Masson",
    appelation: "Apremont",
    region: "Savoie",
    annee: 2020,
    alcool: 13.5,
    cepages: [{ cepage: "Jacquère", pourcentage: 90 },{ cepage: "Jacquère2", pourcentage: 10 }],
    noteClem: 5,
    noteBen: 4,
    commentClem: "Bonne qualité de vin, goût bien frais, bonne éclaircie, très bonne bouteille, bonne goût, très bon goût",
    commentBen: "Bonne qualité de vin, bonne éclaircie, très bonne bouteille, bonne goût, très bon goût",
  },
  {
    id: "pic_saint_loup",
    date: new Date("2024-04-12"),
    bu: true,
    image: "",
    type: "vin rouge",
    domaine: "Domaine de Sigalière",
    appelation: "Pic Saint Loup",
    region: "Languedoc-Roussillon",
    annee: 2023,
    alcool: 14,
    cepages: [{ cepage: "Syrah", pourcentage: 60 }, { cepage: "Grenache", pourcentage: 25 }, { cepage: "Mourvèdre", pourcentage: 15 }],
    noteClem: 5,
    noteBen: 4,
    commentClem: "Bonne qualité de vin, goût bien frais, bonne éclaircie, très bonne bouteille, bonne goût, très bon goût",
    commentBen: "Bonne qualité de vin, bonne éclaircie, très bonne bouteille, bonne goût, très bon goût",
  },
  {
    id: "vinsobres",
    bu: false,
    type: "vin rouge",
    appelation: "Vinsobres",
    region: "Côtes du Rhône Méridional",
  },
  {
    id: "cairanne",
    bu: false,
    type: "vin rouge",
    appelation: "Cairanne",
    region: "Côtes du Rhône Méridional",
  },
  {
    id: "rasteau",
    bu: false,
    type: "vin rouge",
    appelation: "Rasteau",
    region: "Côtes du Rhône Méridional",
  },
  {
    id: "gigondas",
    bu: false,
    type: "vin rouge",
    appelation: "Gigondas",
    region: "Côtes du Rhône Méridional",
  },
  {
    id: "vacqueyras",
    bu: false,
    type: "vin rouge",
    appelation: "Vacqueyras",
    region: "Côtes du Rhône Méridional",
  },
  {
    id: "chateauneuf_du_pape",
    bu: false,
    type: "vin rouge",
    appelation: "Châteauneuf du Pape",
    region: "Côtes du Rhône Méridional",
  },
  {
    id: "lirac",
    bu: false,
    type: "vin rouge",
    appelation: "Lirac",
    region: "Côtes du Rhône Méridional",
  },
  {
    id: "costieres_de_nimes",
    bu: false,
    type: "vin rouge",
    appelation: "Costières de Nîmes",
    region: "Côtes du Rhône Méridional",
  }
]